trigger:
- main

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires


pool:
  vmImage: windows-latest

variables:
- name: semanticVersion
  value: $[counter(variables['majorMinorVersion'], 0)]
- name: solution
  value: 'dglambert.SitecoreAnnotatable.sln' 
- name: buildPlatform
  value: 'Any CPU'  
- name: buildConfiguration
  value: 'Release' 
- name: nuspecPath
  value: '**\dglambert.SitecoreAnnotatable.Infrastructure.csproj'  

steps:

- task: NuGetToolInstaller@1
  displayName: 'Acquires a specific version of NuGet from the internet or the tools cache'

- task: NuGetCommand@2
  displayName: 'Restore Solution Package'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)
    feedsToUse: 'config'

- task: SonarCloudPrepare@1
  displayName: 'Sonar Cloud Prepare Step for Analysis'
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'dglambert'
    scannerMode: 'MSBuild'
    projectKey: 'dglambert_sitecoreannotatable'
    projectName: 'dglambert'

- task: VSBuild@1
  displayName: 'Solution Build'
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
  
- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\dglambert.SitecoreAnnotatable.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(build.sourcesdirectory)'
    codeCoverageEnabled: true

- task: SonarCloudAnalyze@1
  displayName: 'Sonarcloud Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish Sonarcloud Report'
  inputs:
    pollingTimeoutSec: '300'

- task: NuGetCommand@2
  displayName: 'Pack Nuspec'
  inputs:
    command: 'pack'
    packagesToPack: '$(nuspecPath)'
    versioningScheme: 'byBuildNumber'
    configuration: $(buildConfiguration)

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'Push Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'dglambertNuget'
    externalFeedCredentials: 'dglambertNuget'