trigger:
- main

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires


pool:
  vmImage: windows-latest

variables:
- name: semanticVersion
  value: $[counter(variables['majorMinorVersion'], 0)]
- name: solution
  value: 'dglambert.SitecoreAnnotatable.sln' 
- name: buildPlatform
  value: 'Any CPU'  
- name: buildConfiguration
  value: 'Release' 
- name: nuspecPath
  value: '**\dglambert.SitecoreAnnotatable.Infrastructure.nuspec'  

steps:

- task: NuGetToolInstaller@1
  displayName: 'Acquires a specific version of NuGet from the internet or the tools cache'

- task: NuGetCommand@2
  displayName: 'Restore Solution Package'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)
    feedsToUse: 'config'

- task: VSBuild@1
  displayName: 'Solution Build'
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
  
- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\dglambert.SitecoreAnnotatable.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(build.sourcesdirectory)'
    codeCoverageEnabled: true

- task: NuGetCommand@2
  displayName: 'Pack Nuspec'
  inputs:
    command: 'pack'
    packagesToPack: '$(nuspecPath)'
    versioningScheme: 'byBuildNumber'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'Push Package'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'dglambertNuget'
    externalFeedCredentials: 'dglambertNuget'